### ISSUE TITLE
Error while extending Date

### ISSUE THREAD

**Issue by adius** [loganfsmyth/babel-plugin-transform-builtin-extend#3] opened 2016-03-08 16:09 UTC
I try to extend the Date object and get following error:

```
ReferenceError: Reflect is not defined
```

and it highlights following line:

```
var instance = Reflect.construct(cls, Array.from(arguments));
		               ^
```

The file:

```js
export default class Instant extends Date {
	constructor () {
		super()
	}
}
```

**Comment by zloirock** [comment] 2016-03-08 16:13
#2

**Comment by loganfsmyth** [comment] 2016-03-08 16:20
Yeah, duplicate of https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend/issues/2

**Comment by adius** [comment] 2016-03-08 16:21
You should mention that in the Readme to prevent further issues ;-)

**Closed by loganfsmyth** 2016-03-08 16:20 UTC
